name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]

jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Cache install Nix packages
        uses: rikhuijzer/cache-install@v1.0.8        
        with:
          key: nix-${{ hashFiles('packages.nix') }}
          nix_file: 'ci.nix'
      
      - name: Build peerswap
        run: make build

      - name: Run go tests
        run: make test

      - name: Run tests with integration
        run: make test-integration